[package]
name = "bls_bulletproofs"
version = "1.1.0"
authors = ["Cathie Yun <cathieyun@gmail.com>",
           "Henry de Valence <hdevalence@hdevalence.ca>",
           "Oleg Andreev <oleganza@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/maidsafe/bls_bulletproofs"
categories = ["cryptography"]
keywords = ["cryptography", "crypto", "ristretto", "zero-knowledge", "bulletproofs"]
description = "A pure-Rust implementation of Bulletproofs using Ristretto"
edition = "2018"

[dependencies]
blstrs = "0.6.1"
subtle = { version = "2.4.1", default-features = false }
sha3 = { version = "0.9.1", default-features = false }
rand_chacha = "0.3" # used as a seedable rng in GeneratorsxChain
digest = { version = "0.9.0", default-features = false }
rand = "0.8.5"
byteorder = { version = "1", default-features = false }
serde = { version = "1", default-features = false, features = ["alloc"] }
serde_derive = { version = "1", default-features = false }
thiserror = { version = "1", optional = true }
merlin = { version = "3", default-features = false }
clear_on_drop = { version = "0.2", default-features = false }
group = "0.12.0"

[dev-dependencies]
hex = "0.3"
criterion = "0.3"
bincode = "1"
rand_chacha = "0.3"

[features]
default = ["std"]
yoloproofs = []
std = ["thiserror"]
nightly = ["subtle/nightly", "clear_on_drop/nightly"]
docs = ["nightly"]

[[test]]
name = "range_proof"

[[test]]
name = "r1cs"
required-features = ["yoloproofs"]

[[bench]]
name = "range_proof"
harness = false

[[bench]]
name = "generators"
harness = false

[[bench]]
name = "r1cs"
harness = false
required-features = ["yoloproofs"]
